In [11]:
import warnings
import koreanize_matplotlib
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import ast

# 경고 무시
warnings.filterwarnings("ignore")
%config lnlineBackend.figure_format = 'retina'

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)  # 출력할 너비를 넉넉하게 조정
pd.set_option('display.expand_frame_repr', False)  # 옆으로 길어져도 줄바꿈 없이 출력
pd.set_option('display.max_colwidth', None)  # 긴 문자열도 생략 없이 출력

In [2]:
API_KEY_PATH ='/home/project_yujin/high_project/sprintda03-yujin.json'

def get_df(db_name, table_name):
    if table_name == 'hackle_events':
        table_name = pd.read_parquet(
            f"gs://high_project/{db_name}/{table_name}.parquet", 
            storage_options={'token' : API_KEY_PATH})
    else:
        table_name = pd.read_csv(
            f"gs://high_project/{db_name}/{table_name}.csv",
            storage_options={'token' : API_KEY_PATH}
            )
    return table_name

In [6]:
hackle_events = get_df('hackle','hackle_events')

In [16]:
hackle_events.isna().sum()

event_id                 0
event_datetime           0
event_key                0
session_id               0
id                       0
item_name                0
page_name                0
friend_count        752556
votes_count         754554
heart_balance       728643
question_id       10991835
dtype: int64

In [ ]:

wow = [i for i in hackle_properties['user_id'].unique().tolist() if not i.isdigit()]

                                      event_id      event_datetime                        event_key                            session_id                                    id item_name page_name  friend_count  votes_count  heart_balance  question_id
0         00000533-3f1c-4b3b-81f1-0c8f35754b4e 2023-07-18 19:40:17                   $session_start          4OzYh3seq3VKytpSn5pvQkZNQii1  00000533-3f1c-4b3b-81f1-0c8f35754b4e                               NaN          NaN            NaN          NaN
1         00000716-27e9-4e72-a602-d0ce61784b06 2023-07-18 21:07:24              click_question_open          8QXy31PQxbW9qLzq0Y1dhR8Ypm52  00000716-27e9-4e72-a602-d0ce61784b06                              64.0        436.0         4830.0          NaN
2         000007c8-68ce-40e6-9b1e-f0e34e8ff9cc 2023-08-06 20:18:03  click_bottom_navigation_profile  6bcea65d-9f40-46fc-888c-700fe707483f  000007c8-68ce-40e6-9b1e-f0e34e8ff9cc                              26.0        174.0         4729.0          NaN
3         00000981-5e2a-4111-993e-4f1891ad9a53 2023-08-05 01:46:10                        view_shop          XVYNT6zfhFWqIg9omwg2AHDjTLx2  00000981-5e2a-4111-993e-4f1891ad9a53                              61.0         44.0          142.0          NaN
4         00000a7a-ba72-4332-b4a9-7910670aaeb2 2023-07-24 15:03:37      click_bottom_navigation_lab          XFB2SPiGfjbVhvJ3Q3DBsaT3m2B3  00000a7a-ba72-4332-b4a9-7910670aaeb2                             119.0        545.0         3287.0          NaN
...                                        ...                 ...                              ...                                   ...                                   ...       ...       ...           ...          ...            ...          ...
11441314  fffff54e-e730-418f-8080-4eff7e2641f2 2023-08-08 01:40:00                view_timeline_tap          n9RSY5wNfvURIV3sKeXZiYWiVSD3  fffff54e-e730-418f-8080-4eff7e2641f2                              27.0         92.0          326.0          NaN
11441315  fffff57d-6c79-46b3-a87b-4bfa900ef11b 2023-07-23 09:30:22                    skip_question  CB3F11FD-4B78-4496-96E7-3B4174C123E9  fffff57d-6c79-46b3-a87b-4bfa900ef11b                               0.0          0.0          300.0        799.0
11441316  fffff632-2d70-4190-addd-6ae2f2399876 2023-07-18 18:13:30                     view_lab_tap          AwpRr0ll7bTfFV22MIXHDASEpz72  fffff632-2d70-4190-addd-6ae2f2399876                              29.0         97.0          284.0          NaN
11441317  fffffb07-af2f-4cce-a26e-1dcc97c74b14 2023-07-21 15:37:27                view_timeline_tap          H8oiWwKxRiYByNykbb2GsVYd8JU2  fffffb07-af2f-4cce-a26e-1dcc97c74b14                              49.0        527.0          932.0          NaN
11441318  fffffeac-675f-4c6e-900a-a422ed9bd57c 2023-07-22 02:31:16                   $session_start          4GRqxdquqEPpUFf4w9dNoMHwVCh2  fffffeac-675f-4c6e-900a-a422ed9bd57c                               NaN          NaN            NaN          NaN

[11441319 rows x 11 columns]

In [10]:
(hackle_events['id'] == hackle_events['event_id']).all()

True

In [18]:
hackle_events['item_name'].unique()

array(['', '777 하트', '무료충전소', '1000 하트', '200 하트', '4000 하트'],
      dtype=object)

In [23]:
hackle_events[hackle_events['item_name'] == '777 하트']

                                      event_id      event_datetime       event_key                            session_id                                    id item_name page_name  friend_count  votes_count  heart_balance  question_id
1049      00063238-57cd-4cb5-901e-73fbf0620307 2023-08-07 13:46:19  click_purchase  0f764eda-71d7-416d-ae88-546fdf84caa9  00063238-57cd-4cb5-901e-73fbf0620307    777 하트                    24.0         29.0          508.0          NaN
2350      000e1ff0-fcd7-4cee-b107-29f681f42c59 2023-08-06 21:10:30  click_purchase  F5CF51C8-6251-4C34-9357-94B5E850E920  000e1ff0-fcd7-4cee-b107-29f681f42c59    777 하트                    38.0         18.0          383.0          NaN
8265      002fec9c-33a0-4621-b8e4-87d166690356 2023-07-25 00:04:28  click_purchase          tQHPSrc5DheXRTVRCxNDhrfE0dn1  002fec9c-33a0-4621-b8e4-87d166690356    777 하트                    48.0        657.0          205.0          NaN
8626      00322e58-a228-467c-9044-e17d81025005 2023-07-29 18:38:41  click_purchase          qmQXDWallYWIOCTSp7aQKckG3rv2  00322e58-a228-467c-9044-e17d81025005    777 하트                    68.0        209.0          139.0          NaN
12071     004603b7-50e1-40eb-b4e3-c98b33682049 2023-08-07 19:26:41  click_purchase  7df00add-82ed-4fe5-84a1-d5dc85a8e256  004603b7-50e1-40eb-b4e3-c98b33682049    777 하트                    10.0         10.0          165.0          NaN
...                                        ...                 ...             ...                                   ...                                   ...       ...       ...           ...          ...            ...          ...
11429493  ffbb6a63-e1b1-4780-bba3-7db1bd8bb45a 2023-07-21 20:27:57  click_purchase          P0IcSjzoioQoCZatEk2pPeDkU2f1  ffbb6a63-e1b1-4780-bba3-7db1bd8bb45a    777 하트                    41.0         84.0          525.0          NaN
11430136  ffbf5eff-93ce-4323-980a-72401faf577b 2023-07-20 09:18:02  click_purchase  a977d955-e9f8-4d94-8ddc-f79ea0b87e69  ffbf5eff-93ce-4323-980a-72401faf577b    777 하트                    14.0          3.0          160.0          NaN
11433036  ffcfcefb-7d08-41b3-ac78-dfa68a29c2cd 2023-07-18 21:37:07  click_purchase          Zqhwt3dF41OwgGb9k4rATenAQoj2  ffcfcefb-7d08-41b3-ac78-dfa68a29c2cd    777 하트                    33.0        144.0          201.0          NaN
11437257  ffe83dc0-0b13-456a-9b82-3fc3f06f683f 2023-07-21 13:57:51  click_purchase          u3mgNdjImCfmRV4VEHPEKiszL3C3  ffe83dc0-0b13-456a-9b82-3fc3f06f683f    777 하트                    94.0        246.0          147.0          NaN
11438237  ffede6f6-0bf1-4b63-a53d-8efaf437a962 2023-08-06 22:28:59  click_purchase          aMpH5DM7dLgGEi8SPycVx4U57CG2  ffede6f6-0bf1-4b63-a53d-8efaf437a962    777 하트                     7.0          4.0          113.0          NaN

[3258 rows x 11 columns]

In [20]:
hackle_events['page_name'].unique()

array(['', 'notice', 'home', 'profile', '학교선택', '학년선택', '반선택', '번호인증',
       '성별선택', '아이디입력', '프사설정', 'invite', '이름입력'], dtype=object)

In [ ]:
hackle_events['page_name'].unique()