In [2]:
# !pip install koreanize_matplotlib

import warnings
import koreanize_matplotlib
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as  plt
from matplotlib_venn import venn2
import plotly.express as px
import plotly.graph_objects as go
import ast


# 그래프 해상도 높이기
try:
    %config InlineBackend.figure_format = 'retina'
except Exception as e:
    print(f'💩 {e}')



# 경고 무시
warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)  # 출력할 너비를 넉넉하게 조정
pd.set_option('display.expand_frame_repr', False)  # 옆으로 길어져도 줄바꿈 없이 출력
pd.set_option('display.max_colwidth', None)  # 긴 문자열도 생략 없이 출력

try:
    from google.colab import drive
    drive.mount('/content/drive')

    import os
    os.chdir('/content/drive/MyDrive/파트4')
    print('✅ Succesful access google_drive_directory')
    
except Exception as e:
    print('🤗 Hello vscode')
        
## get_df 함수
def get_df(db_name, table_name):
    if table_name in ['accounts_user', 'accounts_blockrecord']:
        table_name = pd.read_parquet(
            f"gs://high_project/{db_name}/{table_name}.parquet", 
            storage_options={'token' : API_KEY_PATH})
    else:
        table_name = pd.read_csv(
            f"gs://high_project/{db_name}/{table_name}.csv",
            storage_options={'token' : API_KEY_PATH}
            )
    return table_name
    

## literal_eval 형변환 함수
def to_literal_eval(df, column):
    return  df[column].apply(lambda x: ast.literal_eval(x) if x != '[]' else [])


# 리스트 내에 드랍 유저가 있는지 확인하는 함수
def find_drop_users(df, column):
    drop_users = [831956, 1580627, 1580689, 1580626, 995177]
    print(f'{column}:')
    for i in drop_users:
        count_drop_rows = len(df[df[column].apply(lambda x: i in x)])
        if count_drop_rows != 0:
            print(f"‼️ 관리자 {i}가 포함된 행 {count_drop_rows}개 존재")
        else:
            print(f"✅ 관리자 {i} 포함행 없음")
            
            
# 데이트타임형으로 변환 및 기간 전처리
def set_datetime(df, column):
    df[column] =  pd.to_datetime(df[column])
    print(f'✅ {column}데이트 타입 형변환 및 기간 전처리 완료')
    
    

            
API_KEY_PATH ='/home/project_yujin/API_KEY/sprintda03-yujin.json'

🤗 Hello vscode

### events: 유저들이 포인트를 얻을수 있었던 이벤트종류

In [47]:
events = get_df('votes', 'events')
set_datetime(events, 'created_at')
events.head()

✅ created_at데이트 타입 형변환 및 기간 전처리 완료

   id           title  plus_point event_type  is_expired          created_at
0   1   코드잇 은행 가입 이벤트         500       FCFS           1 2023-06-20 11:56:38
1   2  코드잇 멤버십 가입 이벤트        1000       FCFS           1 2023-08-08 07:43:45
2   3   예고 영상 기대평 이벤트         500       FCFS           1 2023-09-24 17:05:59

### 15. event_receipts: 유저들이 포인트 이벤트에 참여했던 기록

In [46]:
event_receipts = get_df('votes', 'event_receipts')
event_receipts = event_receipts[['id' ,'user_id' ,'event_id' ,'plus_point' ,'created_at']]
set_datetime(event_receipts, 'created_at')
event_receipts = event_receipts.drop(81)
event_receipts.head()

✅ created_at데이트 타입 형변환 및 기간 전처리 완료

   id  user_id  event_id  plus_point          created_at
0   2  1193618         1         500 2023-06-22 09:25:16
1   3   928351         1         500 2023-06-22 09:38:53
2   4   904872         1         500 2023-06-22 10:32:15
3   5   974697         1         500 2023-06-22 13:03:06
4   6  1168260         1         500 2023-06-22 13:40:38

In [ ]:
# # 날자 파생 컬럼 추가
# event_receipts['C_y_m_d'] = event_receipts['created_at'].dt.to_period('D').astype('str')
# event_receipts['C_y_m'] = event_receipts['created_at'].dt.to_period('M').astype('str')
# event_receipts['C_hour'] = event_receipts['created_at'].dt.hour
# event_receipts['C_weekday'] = event_receipts['created_at'].dt.weekday
# event_receipts['C_is_weekend'] = event_receipts['created_at'].dt.weekday >= 5
# event_receipts['C_time_of_day'] = pd.cut(event_receipts['created_at'].dt.hour, bins=[0, 6, 12, 18, 24], labels=['Night', 'Morning', 'Afternoon', 'Evening'], right=False)

In [41]:
# event_id_C_y_m_d = event_receipts.groupby(['event_id'])['C_y_m_d'].value_counts().reset_index().sort_values(by=['event_id', 'C_y_m_d'])

# # 별로 나누기
# event1 = event_id_C_y_m_d[event_id_C_y_m_d['event_id'] == 1]
# event2 = event_id_C_y_m_d[event_id_C_y_m_d['event_id'] == 2]
# event3 = event_id_C_y_m_d[event_id_C_y_m_d['event_id'] == 3]

# fig = go.Figure()

# # event1 라인
# fig.add_trace(go.Scatter(
#     x=event1['C_y_m_d'],
#     y=event1['count'],
#     mode='lines+markers',
#     name='Weekday',
#     line=dict(color='skyblue')
# ))

# # event2 라인
# fig.add_trace(go.Scatter(
#     x=event2['C_y_m_d'],
#     y=event2['count'],
#     mode='lines+markers',
#     name='Weekend',
#     line=dict(color='orange')
# ))

# # event3 라인
# fig.add_trace(go.Scatter(
#     x=event3['C_y_m_d'],
#     y=event3['count'],
#     mode='lines+markers',
#     name='Weekend',
#     line=dict(color='purple')
# ))

# fig.show()

In [ ]:
# event_id_C_hour = event_receipts.groupby(['event_id'])['C_hour'].value_counts().reset_index().sort_values(by=['event_id', 'C_hour'])
# event1 = event_id_C_hour.query('event_id == 1')
# event2 = event_id_C_hour.query('event_id == 2')
# event3 = event_id_C_hour.query('event_id == 3')

# fig = go.Figure()

# # event1 라인
# fig.add_trace(go.Scatter(
#     x=event1['C_hour'],
#     y=event1['count'],
#     mode='lines+markers',
#     name='',
#     line=dict(color='skyblue')
# ))

# # event2 라인
# fig.add_trace(go.Scatter(
#     x=event2['C_hour'],
#     y=event2['count'],
#     mode='lines+markers',
#     name='',
#     line=dict(color='orange')
# ))

# # event3 라인ㅁ
# fig.add_trace(go.Scatter(
#     x=event3['C_hour'],
#     y=event3['count'],
#     mode='lines+markers',
#     name='',
#     line=dict(color='purple')
# ))
# fig.update_layout(
#     title='이벤트별 참가시간대',
#     xaxis_title='Hour of Day',
#     yaxis_title='Count',
#     xaxis=dict(tickmode='linear', dtick=1),
#     template='plotly_white',
#     width=1000,
#     height=500
# )

# fig.show()

In [ ]:
# from datetime import timedelta
# kst = event_receipts[['event_id', 'created_at']]
# kst['kst_created_at'] = pd.to_datetime(kst['created_at'], utc=True) + timedelta(hours=9)

# kst['C_y_m_d'] = kst['kst_created_at'].dt.to_period('D').astype('str')
# kst['C_y_m'] = kst['kst_created_at'].dt.to_period('M').astype('str')
# kst['C_hour'] = kst['kst_created_at'].dt.hour
# kst['C_weekday'] = kst['kst_created_at'].dt.weekday
# kst['C_is_weekend'] = kst['kst_created_at'].dt.weekday >= 5
# kst['C_time_of_day'] = pd.cut(kst['kst_created_at'].dt.hour, bins=[0, 6, 12, 18, 24], labels=['Night', 'Morning', 'Afternoon', 'Evening'], right=False)

In [ ]:
# kst_event_id_C_hour = kst.groupby(['event_id'])['C_hour'].value_counts().reset_index().sort_values(by=['event_id', 'C_hour'])
# kst_event1 = kst_event_id_C_hour.query('event_id == 1')
# kst_event2 = kst_event_id_C_hour.query('event_id == 2')
# kst_event3 = kst_event_id_C_hour.query('event_id == 3')

# fig = go.Figure()

# # event1 라인
# fig.add_trace(go.Scatter(
#     x=kst_event1['C_hour'],
#     y=kst_event1['count'],
#     mode='lines+markers',
#     name='',
#     line=dict(color='skyblue')
# ))

# # event2 라인
# fig.add_trace(go.Scatter(
#     x=kst_event2['C_hour'],
#     y=kst_event2['count'],
#     mode='lines+markers',
#     name='',
#     line=dict(color='orange')
# ))

# # event3 라인ㅁ
# fig.add_trace(go.Scatter(
#     x=kst_event3['C_hour'],
#     y=kst_event3['count'],
#     mode='lines+markers',
#     name='',
#     line=dict(color='purple')
# ))
# fig.update_layout(
#     title='이벤트별 참가시간대',
#     xaxis_title='Hour of Day',
#     yaxis_title='Count',
#     xaxis=dict(tickmode='linear', dtick=1),
#     template='plotly_white',
#     width=1000,
#     height=500
# )

# fig.show()

### accounts_paymenthistory: 포인트 구매기록

In [45]:
accounts_paymenthistory = get_df('votes', 'accounts_paymenthistory')
accounts_paymenthistory.head()

   id  productId phone_type           created_at  user_id
0   6  heart.777          A  2023-05-13 21:28:34  1211127
1   7  heart.777          A  2023-05-13 21:29:39  1151343
2   8  heart.777          A  2023-05-13 21:31:33  1002147
3   9  heart.777          A  2023-05-13 21:31:39  1095040
4  11  heart.777          A  2023-05-13 21:34:32  1164081

### accounts_failpaymenthistory: 포인트 결제 실패 기록

In [44]:
accounts_failpaymenthistory = get_df('votes', 'accounts_failpaymenthistory')
accounts_failpaymenthistory.head()

   id   productId phone_type           created_at  user_id
0   6   heart.200          A  2023-05-14 05:49:22  1055891
1   7   heart.777          A  2023-05-14 08:17:21  1152151
2   8   heart.777          A  2023-05-14 10:11:46   986200
3   9  heart.1000          A  2023-05-14 11:53:09  1028261
4  10   heart.777          A  2023-05-14 12:30:47  1235730

### accounts_pointhistory: 포인트 충전 및 사용에 대한 기록

In [133]:
accounts_pointhistory = get_df('votes', 'accounts_pointhistory')
accounts_pointhistory = accounts_pointhistory[['id', 'user_id', 'user_question_record_id', 'delta_point', 'created_at']]
accounts_pointhistory.head()

       id  user_id  user_question_record_id  delta_point           created_at
0  790629   849436                 771777.0            9  2023-04-28 12:27:49
1  790652   849436                 771800.0            9  2023-04-28 12:28:02
2  790664   849436                 771812.0            5  2023-04-28 12:28:09
3  790680   849436                 771828.0           13  2023-04-28 12:28:16
4  790703   849436                 771851.0            5  2023-04-28 12:28:26

In [109]:
accounts_pointhistory.loc[:, [ 'user_id', 'user_question_record_id', 'delta_point', 'created_at']].duplicated().sum()
accounts_pointhistory.loc[:, [ 'user_id', 'user_question_record_id', 'delta_point', 'created_at']].duplicated(keep=False).sum()

0

In [108]:
accounts_pointhistory = accounts_pointhistory[~accounts_pointhistory.loc[:, [ 'user_id', 'user_question_record_id', 'delta_point', 'created_at']].duplicated()]

In [115]:
accounts_pointhistory[accounts_pointhistory['delta_point'] > 0]['delta_point'].unique()

array([   9,    5,   13,   10,   12,   15,   14,    8,    6,   11,    7,
        200,  500, 1000,  300,  210,  240,  220,  230,  250,  777,  260,
        270,  280,  100,   50,   60,   70,   80,   90,  110,  120,  130,
        140,  150,  160,  170,  180])

In [132]:
mask = pd.to_numeric(accounts_pointhistory['user_question_record_id'], errors='coerce').isnull()
accounts_pointhistory[mask]['delta_point'].value_counts()

delta_point
 200     1368
 500      429
 50       322
 1000     233
 300      180
 210      127
 220       64
 60        47
 230       36
 240       26
 250       20
 777       19
 70        16
 260       14
 270       12
 80        10
 100       10
 280       10
 90         7
 110        6
 120        6
 130        5
 140        4
 150        4
 160        4
 170        3
 180        3
-30         1
Name: count, dtype: int64

In [ ]:
accounts_pointhistory[accounts_pointhistory['delta_point'] > 0]['user_question_record_id'].unique().tolist()

[771777.0,
 771800.0,
 771812.0,
 771828.0,
 771851.0,
 771864.0,
 771894.0,
 771908.0,
 771912.0,
 771927.0,
 771940.0,
 771952.0,
 771966.0,
 771969.0,
 771974.0,
 771981.0,
 771995.0,
 772001.0,
 772002.0,
 772023.0,
 772025.0,
 772027.0,
 772030.0,
 772040.0,
 772044.0,
 772054.0,
 772056.0,
 772057.0,
 772080.0,
 772088.0,
 772098.0,
 772101.0,
 772106.0,
 772122.0,
 772123.0,
 772126.0,
 772128.0,
 772133.0,
 772140.0,
 772147.0,
 772150.0,
 772151.0,
 772157.0,
 772167.0,
 772168.0,
 772179.0,
 772184.0,
 772190.0,
 772195.0,
 772203.0,
 772214.0,
 772223.0,
 772225.0,
 772226.0,
 772233.0,
 772241.0,
 772246.0,
 772258.0,
 772268.0,
 772277.0,
 772278.0,
 772279.0,
 772289.0,
 772293.0,
 772297.0,
 772299.0,
 772300.0,
 772301.0,
 772309.0,
 772314.0,
 772315.0,
 772320.0,
 772332.0,
 772334.0,
 772343.0,
 772346.0,
 772359.0,
 772360.0,
 772364.0,
 772370.0,
 772386.0,
 772389.0,
 772395.0,
 772398.0,
 772414.0,
 772416.0,
 772426.0,
 772434.0,
 772439.0,
 772453.0,
 772457.0,
 772470.0,
 772472.0,
 772474.0,
 772484.0,
 772488.0,
 772493.0,
 772499.0,
 772501.0,
 772506.0,
 772512.0,
 772521.0,
 772530.0,
 772537.0,
 772541.0,
 772554.0,
 772557.0,
 772559.0,
 772564.0,
 772567.0,
 772583.0,
 772590.0,
 772594.0,
 772599.0,
 772604.0,
 772619.0,
 772626.0,
 772628.0,
 772629.0,
 772639.0,
 772646.0,
 772661.0,
 772665.0,
 772666.0,
 772672.0,
 772681.0,
 772683.0,
 772689.0,
 772713.0,
 772721.0,
 772726.0,
 772750.0,
 772756.0,
 772759.0,
 772767.0,
 772773.0,
 772780.0,
 772796.0,
 772830.0,
 772836.0,
 772840.0,
 772850.0,
 772852.0,
 772875.0,
 772911.0,
 772938.0,
 772959.0,
 773020.0,
 773026.0,
 773041.0,
 773047.0,
 773083.0,
 773123.0,
 773144.0,
 773151.0,
 773166.0,
 773180.0,
 773189.0,
 773206.0,
 773222.0,
 773246.0,
 773259.0,
 773270.0,
 773284.0,
 773303.0,
 773322.0,
 773355.0,
 773747.0,
 773843.0,
 773862.0,
 773894.0,
 773972.0,
 773997.0,
 774049.0,
 774066.0,
 774110.0,
 774118.0,
 774124.0,
 774132.0,
 774152.0,
 774170.0,
 774188.0,
 774209.0,
 774235.0,
 774259.0,
 774271.0,
 774282.0,
 774291.0,
 774295.0,
 774309.0,
 774314.0,
 774329.0,
 774332.0,
 774335.0,
 774375.0,
 774394.0,
 774486.0,
 774507.0,
 774517.0,
 774544.0,
 774559.0,
 774581.0,
 774602.0,
 774622.0,
 774876.0,
 775046.0,
 775066.0,
 775102.0,
 775127.0,
 775152.0,
 775176.0,
 775205.0,
 775292.0,
 775335.0,
 775366.0,
 775410.0,
 775430.0,
 775488.0,
 775611.0,
 775634.0,
 775696.0,
 775726.0,
 775749.0,
 775756.0,
 775765.0,
 775781.0,
 775815.0,
 775830.0,
 775853.0,
 775872.0,
 775875.0,
 775879.0,
 775890.0,
 775903.0,
 775906.0,
 775917.0,
 775927.0,
 775931.0,
 775950.0,
 775959.0,
 775971.0,
 775980.0,
 776104.0,
 776106.0,
 776127.0,
 776131.0,
 776134.0,
 776148.0,
 776163.0,
 776164.0,
 776181.0,
 776183.0,
 776192.0,
 776212.0,
 776226.0,
 776229.0,
 776234.0,
 776255.0,
 776261.0,
 776264.0,
 776276.0,
 776314.0,
 776335.0,
 776350.0,
 776370.0,
 776375.0,
 776396.0,
 776423.0,
 776456.0,
 776468.0,
 776484.0,
 776491.0,
 776522.0,
 776540.0,
 776554.0,
 776624.0,
 776632.0,
 776646.0,
 776658.0,
 776823.0,
 776850.0,
 776869.0,
 776903.0,
 776913.0,
 776994.0,
 777012.0,
 777021.0,
 777049.0,
 777089.0,
 777104.0,
 777128.0,
 777133.0,
 777166.0,
 777173.0,
 777181.0,
 777182.0,
 777185.0,
 777195.0,
 777205.0,
 777219.0,
 777232.0,
 777249.0,
 777258.0,
 777272.0,
 777286.0,
 777332.0,
 777358.0,
 777375.0,
 777432.0,
 777448.0,
 777473.0,
 777485.0,
 777511.0,
 777570.0,
 777643.0,
 777661.0,
 777678.0,
 777681.0,
 777719.0,
 777731.0,
 777775.0,
 777797.0,
 777801.0,
 777825.0,
 777833.0,
 777846.0,
 777847.0,
 777858.0,
 777880.0,
 777902.0,
 777913.0,
 777949.0,
 777953.0,
 777978.0,
 778005.0,
 778038.0,
 778060.0,
 778061.0,
 778081.0,
 778084.0,
 778104.0,
 778111.0,
 778113.0,
 778142.0,
 778165.0,
 778243.0,
 778293.0,
 778296.0,
 778302.0,
 778309.0,
 778335.0,
 778376.0,
 778391.0,
 778580.0,
 778695.0,
 778777.0,
 778782.0,
 778793.0,
 778824.0,
 778860.0,
 778880.0,
 779312.0,
 779315.0,
 779331.0,
 779357.0,
 779359.0,
 779373.0,
 779380.0,
 779395.0,
 779398.0,
 779407.0,
 779412.0,
 779414.0,
 779436.0,
 779447.0,
 779459.0,
 779487.0,
 779488.0,
 779508.0,
 779509.0,
 779513.0,
 779528.0,
 779533.0,
 779537.0,
 779546.0,
 779555.0,
 779557.0,
 779564.0,
 779577.0,
 779578.0,
 779582.0,
 779589.0,
 779590.0,
 779594.0,
 779601.0,
 779614.0,
 779618.0,
 779630.0,
 779635.0,
 779643.0,
 779650.0,
 779666.0,
 779669.0,
 779670.0,
 779680.0,
 779691.0,
 779694.0,
 779698.0,
 779710.0,
 779712.0,
 779726.0,
 779742.0,
 779749.0,
 779764.0,
 779767.0,
 779813.0,
 779818.0,
 779820.0,
 779832.0,
 779849.0,
 779862.0,
 779870.0,
 779891.0,
 779897.0,
 779917.0,
 779918.0,
 779930.0,
 779931.0,
 779938.0,
 779942.0,
 779947.0,
 779964.0,
 779968.0,
 779972.0,
 779999.0,
 780000.0,
 780001.0,
 780006.0,
 780012.0,
 780017.0,
 780049.0,
 780060.0,
 780065.0,
 780071.0,
 780080.0,
 780084.0,
 780091.0,
 780096.0,
 780103.0,
 780106.0,
 780126.0,
 780127.0,
 780137.0,
 780153.0,
 780159.0,
 780171.0,
 780180.0,
 780188.0,
 780193.0,
 780199.0,
 780208.0,
 780211.0,
 780221.0,
 780229.0,
 780232.0,
 780255.0,
 780258.0,
 780275.0,
 780280.0,
 780282.0,
 780309.0,
 780312.0,
 780317.0,
 780337.0,
 780343.0,
 780355.0,
 780363.0,
 780369.0,
 780373.0,
 780375.0,
 780383.0,
 780394.0,
 780406.0,
 780410.0,
 780422.0,
 780431.0,
 780434.0,
 780450.0,
 780453.0,
 780455.0,
 780474.0,
 780478.0,
 780489.0,
 780493.0,
 780505.0,
 780512.0,
 780516.0,
 780520.0,
 780532.0,
 780535.0,
 780545.0,
 780553.0,
 780568.0,
 780589.0,
 780591.0,
 780606.0,
 780612.0,
 780624.0,
 780629.0,
 780640.0,
 780657.0,
 780679.0,
 780692.0,
 780693.0,
 780701.0,
 780718.0,
 780770.0,
 780806.0,
 780847.0,
 780858.0,
 780871.0,
 780880.0,
 780889.0,
 780894.0,
 780895.0,
 780905.0,
 780912.0,
 780913.0,
 780924.0,
 780931.0,
 780935.0,
 780939.0,
 780940.0,
 780949.0,
 780956.0,
 780959.0,
 780962.0,
 780971.0,
 780978.0,
 780988.0,
 780993.0,
 780995.0,
 781004.0,
 781020.0,
 781033.0,
 781034.0,
 781051.0,
 781223.0,
 781250.0,
 781280.0,
 781342.0,
 781361.0,
 781414.0,
 781438.0,
 781468.0,
 781525.0,
 781567.0,
 781588.0,
 781713.0,
 781820.0,
 781919.0,
 781942.0,
 781979.0,
 782008.0,
 782028.0,
 782049.0,
 782095.0,
 782110.0,
 782121.0,
 782131.0,
 782139.0,
 782140.0,
 782155.0,
 782165.0,
 782167.0,
 782181.0,
 782183.0,
 782192.0,
 782197.0,
 782217.0,
 782225.0,
 782248.0,
 782249.0,
 782252.0,
 782269.0,
 782271.0,
 782275.0,
 782281.0,
 782283.0,
 782287.0,
 782303.0,
 782309.0,
 782310.0,
 782321.0,
 782332.0,
 782340.0,
 782343.0,
 782350.0,
 782358.0,
 782363.0,
 782368.0,
 782391.0,
 782400.0,
 782414.0,
 782430.0,
 782509.0,
 782527.0,
 782544.0,
 782547.0,
 782561.0,
 782578.0,
 782600.0,
 782619.0,
 782692.0,
 782700.0,
 782757.0,
 782779.0,
 782799.0,
 782835.0,
 782857.0,
 782866.0,
 782887.0,
 782924.0,
 782929.0,
 782994.0,
 783005.0,
 783008.0,
 783027.0,
 783048.0,
 783051.0,
 783064.0,
 783074.0,
 783089.0,
 783098.0,
 783116.0,
 783123.0,
 783150.0,
 783204.0,
 783251.0,
 783260.0,
 783340.0,
 783363.0,
 783384.0,
 783426.0,
 783429.0,
 783440.0,
 783448.0,
 783451.0,
 783463.0,
 783465.0,
 783476.0,
 783479.0,
 783494.0,
 783501.0,
 783505.0,
 783521.0,
 783526.0,
 783544.0,
 783557.0,
 783588.0,
 783589.0,
 783609.0,
 783666.0,
 783678.0,
 783691.0,
 783703.0,
 783744.0,
 783773.0,
 783789.0,
 783802.0,
 783925.0,
 783945.0,
 783964.0,
 784030.0,
 784079.0,
 784085.0,
 784102.0,
 784153.0,
 784182.0,
 784203.0,
 784230.0,
 784243.0,
 784265.0,
 784286.0,
 784292.0,
 784319.0,
 784355.0,
 784357.0,
 784361.0,
 784373.0,
 784382.0,
 784403.0,
 784408.0,
 784417.0,
 784514.0,
 784549.0,
 784572.0,
 784586.0,
 784659.0,
 784711.0,
 784732.0,
 784736.0,
 784767.0,
 784773.0,
 784776.0,
 784794.0,
 784797.0,
 784798.0,
 784819.0,
 784824.0,
 784828.0,
 784841.0,
 784845.0,
 784848.0,
 784863.0,
 784869.0,
 784879.0,
 784887.0,
 784891.0,
 784899.0,
 784911.0,
 784917.0,
 784923.0,
 784924.0,
 784930.0,
 784952.0,
 784956.0,
 784958.0,
 784977.0,
 784983.0,
 785009.0,
 785010.0,
 785051.0,
 785128.0,
 785131.0,
 785134.0,
 785144.0,
 785149.0,
 785159.0,
 785161.0,
 785163.0,
 785179.0,
 785187.0,
 785217.0,
 785236.0,
 785277.0,
 785299.0,
 785303.0,
 785332.0,
 785337.0,
 785362.0,
 785378.0,
 785393.0,
 785416.0,
 785427.0,
 785439.0,
 785441.0,
 785448.0,
 785454.0,
 785457.0,
 785459.0,
 785461.0,
 785473.0,
 785476.0,
 785480.0,
 785494.0,
 785495.0,
 785507.0,
 785519.0,
 785536.0,
 785565.0,
 785591.0,
 785624.0,
 785650.0,
 785691.0,
 785700.0,
 785716.0,
 785737.0,
 785753.0,
 785764.0,
 785777.0,
 785794.0,
 785805.0,
 785812.0,
 785819.0,
 785832.0,
 785843.0,
 785844.0,
 785845.0,
 785880.0,
 785895.0,
 785911.0,
 785935.0,
 785989.0,
 786028.0,
 786054.0,
 786072.0,
 786194.0,
 786234.0,
 786284.0,
 786305.0,
 786316.0,
 786337.0,
 786399.0,
 786438.0,
 786450.0,
 786454.0,
 786460.0,
 786475.0,
 786495.0,
 786505.0,
 786513.0,
 786536.0,
 786540.0,
 786549.0,
 786551.0,
 786568.0,
 786569.0,
 786581.0,
 786610.0,
 786611.0,
 786622.0,
 786634.0,
 786647.0,
 786656.0,
 786667.0,
 786674.0,
 786694.0,
 786701.0,
 786708.0,
 786718.0,
 786730.0,
 786746.0,
 786756.0,
 786785.0,
 786803.0,
 786807.0,
 786820.0,
 786824.0,
 786855.0,
 786857.0,
 786867.0,
 786868.0,
 786873.0,
 786881.0,
 786894.0,
 786913.0,
 786935.0,
 786943.0,
 786953.0,
 786955.0,
 786971.0,
 786972.0,
 786974.0,
 786984.0,
 786986.0,
 786995.0,
 787006.0,
 787017.0,
 787027.0,
 787036.0,
 787047.0,
 787082.0,
 787085.0,
 787133.0,
 787137.0,
 787199.0,
 787231.0,
 787258.0,
 787267.0,
 787274.0,
 787284.0,
 787293.0,
 787295.0,
 787303.0,
 787307.0,
 787314.0,
 787326.0,
 787347.0,
 787359.0,
 787378.0,
 787435.0,
 787442.0,
 787459.0,
 787467.0,
 787477.0,
 787484.0,
 787497.0,
 787503.0,
 787520.0,
 787529.0,
 787554.0,
 787562.0,
 787585.0,
 787589.0,
 787599.0,
 787618.0,
 787640.0,
 787653.0,
 787657.0,
 787676.0,
 787687.0,
 787693.0,
 787701.0,
 787706.0,
 787723.0,
 787726.0,
 787746.0,
 787755.0,
 787765.0,
 787773.0,
 787783.0,
 787795.0,
 787812.0,
 787826.0,
 787829.0,
 787838.0,
 787846.0,
 787850.0,
 787868.0,
 787869.0,
 787872.0,
 787884.0,
 787890.0,
 787912.0,
 787926.0,
 787933.0,
 787950.0,
 787965.0,
 787968.0,
 787984.0,
 787990.0,
 787994.0,
 788007.0,
 788011.0,
 788014.0,
 788018.0,
 788032.0,
 788043.0,
 788064.0,
 788065.0,
 788072.0,
 788088.0,
 788091.0,
 788098.0,
 788106.0,
 788115.0,
 788126.0,
 788146.0,
 788147.0,
 788150.0,
 788162.0,
 788171.0,
 788200.0,
 788213.0,
 788215.0,
 788254.0,
 788264.0,
 788278.0,
 788292.0,
 788313.0,
 788315.0,
 788336.0,
 788343.0,
 788351.0,
 788362.0,
 788372.0,
 788380.0,
 788383.0,
 788387.0,
 788395.0,
 788398.0,
 788406.0,
 788414.0,
 788420.0,
 788425.0,
 788439.0,
 788449.0,
 788450.0,
 788454.0,
 788466.0,
 788470.0,
 788472.0,
 788475.0,
 788478.0,
 788480.0,
 788483.0,
 788490.0,
 788494.0,
 788503.0,
 788504.0,
 788509.0,
 788518.0,
 788519.0,
 788522.0,
 788531.0,
 788542.0,
 788549.0,
 788551.0,
 788562.0,
 ...]

### accounts_userquestionrecord: 투표기록 테이블

In [ ]:
accounts_userquestionrecord = get_df('votes', 'accounts_userquestionrecord')
accounts_userquestionrecord = accounts_userquestionrecord[['id', 'user_id', 'chosen_user_id', 'question_id', 'question_piece_id', \
    'status' ,'answer_status', 'answer_updated_at', 'has_read', 'opened_times', 'report_count', 'created_at']]

       id  user_id  chosen_user_id  question_id  question_piece_id status answer_status    answer_updated_at  has_read  opened_times  report_count           created_at
0  771777   849436          849469          252             998458     닫힘             N  2023-04-28 12:27:49         0             0             0  2023-04-28 12:27:49
1  771800   849436          849446          244             998459     닫힘             N  2023-04-28 12:28:02         0             0             0  2023-04-28 12:28:02
2  771812   849436          849454          183             998460     닫힘             N  2023-04-28 12:28:09         1             0             0  2023-04-28 12:28:09
3  771828   849436          847375          101             998461     닫힘             N  2023-04-28 12:28:16         0             0             0  2023-04-28 12:28:16
4  771851   849436          849477          209             998462     닫힘             N  2023-04-28 12:28:26         1             0             0  2023-04-28 12:28:26

In [71]:
accounts_userquestionrecord['status'] = accounts_userquestionrecord['status'].replace({'C':'닫힘'}).replace({'I':'초성열림'}).replace({'B':'차단'})
accounts_userquestionrecord['answer_status'] = accounts_userquestionrecord['answer_status'].replace({'N':'미답변'}).replace({'P':'비공개'}).replace({'A':'공개'})
set_datetime(accounts_userquestionrecord, 'answer_updated_at')
set_datetime(accounts_userquestionrecord, 'created_at')
accounts_userquestionrecord['diff_time'] = accounts_userquestionrecord['answer_updated_at'] - accounts_userquestionrecord['created_at']
accounts_userquestionrecord['diff_sec_time'] = (accounts_userquestionrecord['answer_updated_at'] - accounts_userquestionrecord['created_at']).dt.total_seconds()

✅ answer_updated_at데이트 타입 형변환 및 기간 전처리 완료
✅ created_at데이트 타입 형변환 및 기간 전처리 완료

In [72]:
accounts_userquestionrecord[accounts_userquestionrecord.loc[:, ['user_id', 'chosen_user_id' ,'created_at']].duplicated(keep=False)].sort_values(
    by=['user_id', 'chosen_user_id' ,'created_at']
).head()

              id  user_id  chosen_user_id  question_id  question_piece_id status answer_status   answer_updated_at  has_read  opened_times  report_count          created_at diff_time  diff_sec_time
497599  41415258   850096          865629          269           15408091     닫힘           미답변 2023-05-14 04:33:44         1             0             0 2023-05-14 04:33:44    0 days            0.0
497602  41415309   850096          865629          552           15408093     닫힘           미답변 2023-05-14 04:33:44         1             0             0 2023-05-14 04:33:44    0 days            0.0
497557  41411486   855914          867773          390           28683031     닫힘           미답변 2023-05-14 04:33:15         0             0             0 2023-05-14 04:33:15    0 days            0.0
497558  41411496   855914          867773          222           28683036     닫힘           미답변 2023-05-14 04:33:15         0             0             0 2023-05-14 04:33:15    0 days            0.0
470004  38408532   880602          876643          500           49921251     닫힘           미답변 2023-05-13 15:10:36         1             0             0 2023-05-13 15:10:36    0 days            0.0

In [65]:
accounts_userquestionrecord['status'].unique()

array(['닫힘', '초성열림', '차단'], dtype=object)

In [73]:
accounts_userquestionrecord.groupby('answer_status')['diff_sec_time'].mean().reset_index()

  answer_status  diff_sec_time
0            공개   32711.906407
1           미답변      -0.001299
2           비공개   29461.689383

In [76]:
accounts_userquestionrecord.groupby('status')['diff_sec_time'].mean().reset_index()

  status  diff_sec_time
0     닫힘    3077.741957
1     차단     994.922492
2   초성열림    5416.400987

In [80]:
accounts_userquestionrecord.groupby(['has_read', 'answer_status'])['status'].value_counts().reset_index()

    has_read answer_status status   count
0          0           미답변     닫힘  537672
1          0           미답변   초성열림    3629
2          0           미답변     차단     326
3          1            공개     닫힘  101080
4          1            공개   초성열림   10634
5          1            공개     차단      47
6          1           미답변     닫힘  511087
7          1           미답변   초성열림   44937
8          1           미답변     차단     281
9          1           비공개     닫힘    6483
10         1           비공개   초성열림    1378
11         1           비공개     차단       4

In [75]:
accounts_userquestionrecord.groupby('answer_status')['status'].value_counts().reset_index()

  answer_status status    count
0            공개     닫힘   101080
1            공개   초성열림    10634
2            공개     차단       47
3           미답변     닫힘  1048759
4           미답변   초성열림    48566
5           미답변     차단      607
6           비공개     닫힘     6483
7           비공개   초성열림     1378
8           비공개     차단        4

In [ ]:
보낸 유저이름 정확히 보여